### ISSUE TITLE
possibly use a slider to move image?

### ISSUE THREAD

**Issue by owise1** [demand-progress/biden-cabinet-www#11]
use a range field 0-100 for "Adjust Image Left/Right" and "Adjust Image Up/down". append "%" in app. more user friendly

**Comment by csummer** [comment]
Agreed a slider is way more user friendly and requires far less input validation as well.

Would be awesome if there was a wp plugin to click a point on an image and get its x,y percentages automatically!

Maybe there is one but my 2 min of searching has come up dry...
