### ISSUE TITLE
The sign-petition button is visible on some screen sizes before scrolling down

### ISSUE THREAD

**Issue by csummer** [demand-progress/biden-cabinet-www#14]
not sure how many real life form factors this affects, but technically the button will appear if the petition is off-screen, whether that's below the fold or not.

repro: scroll to the top of the page, and resize browser window so that the petition is not visible. Will cause the button at the bottom of the screen to appear.

(I'm seeing in firefox responsive dev mode at ~ 662x417 size -- so again, this may mostly be academic...)

**Comment by owise1** [comment]
N/A
